apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-nginx-conf
  namespace: ${NAMESPACE}
data:
  nginx.conf: |-
    events {
    }

    http {
      server {
        listen 8081;

        if ($http_x_forwarded_proto != 'https') {
          set $redirectHttps Https;
        }

        if ($host ~* ^${DOMAIN}$) {
          set $redirectHttps "${redirectHttps}WithHost";
        }

        if ($redirectHttps = HttpsWithHost) {
          return 301 https://$host$request_uri;
        }

        location / {
          proxy_set_header        Host $host:$server_port;
          proxy_set_header        X-Real-IP $remote_addr;
          proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header        X-Forwarded-Proto $scheme;

          proxy_pass          http://127.0.0.1:${SERVER_PORT};

          proxy_redirect      http://127.0.0.1:${SERVER_PORT} https://${DOMAIN};

          # Required for new HTTP-based CLI
          proxy_http_version 1.1;
          proxy_request_buffering off;
          # workaround for https://issues.jenkins-ci.org/browse/JENKINS-45651
          add_header 'X-SSH-Endpoint' '${DOMAIN}:50022' always;
        }
      }
    }