apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: ${APP_NAME}-tls
  namespace: ${NAMESPACE}
spec:
  secretName: ${APP_NAME}-tls
  issuerRef:
    name: ${CERTIFICATE_ISSUER}
    kind: ClusterIssuer
  commonName: ${DOMAIN}
  dnsNames:
  - ${DOMAIN}
  acme:
    config:
    - http01:
        ingress: ${APP_NAME}
      domains:
      - ${DOMAIN}