apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${APP_NAME}
  namespace: ${NAMESPACE}
spec:
  storageClassName: ""
  capacity:
    storage: ${PERSISTENT_DISK_SIZE}
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: ${PERSISTENT_GCLOUD_DISK_NAME}
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${APP_NAME}
  namespace: ${NAMESPACE}
spec:
  # It's necessary to specify "" as the storageClassName
  # so that the default storage class won't be used, see
  # https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1
  storageClassName: ""
  volumeName: ${APP_NAME}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: ${PERSISTENT_DISK_SIZE}