apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-nginx-conf
  namespace: ${NAMESPACE}
data:
  nginx.conf: |-
    events {
    }

    http {
      server {
        listen ${NGINX_SERVER_PORT};

        if ($http_x_forwarded_proto != 'https') {
          set $redirectHttps Https;
        }

        if ($host ~* ^${DOMAIN}$) {
          set $redirectHttps "${redirectHttps}WithHost";
        }

        if ($redirectHttps = HttpsWithHost) {
          return 301 https://$host$request_uri;
        }

        location / {
          proxy_http_version 1.1;
          proxy_pass http://127.0.0.1:${SERVER_PORT};
          proxy_set_header Host            $host;
          proxy_set_header X-Forwarded-For $remote_addr;
          proxy_redirect     off;
        }
      }
    }